/**
 *
 * $Id$
 */
package gov.sandia.dart.workflow.domain.validation;

import gov.sandia.dart.workflow.domain.Property;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gov.sandia.dart.workflow.domain.NamedObjectWithProperties}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NamedObjectWithPropertiesValidator {
	boolean validate();

	boolean validateProperties(EList<Property> value);
}
