/**
 *
 * $Id$
 */
package gov.sandia.dart.workflow.domain.validation;

import gov.sandia.dart.workflow.domain.Conductor;
import gov.sandia.dart.workflow.domain.InputPort;
import gov.sandia.dart.workflow.domain.OutputPort;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gov.sandia.dart.workflow.domain.WFNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WFNodeValidator {
	boolean validate();

	boolean validateInputPorts(EList<InputPort> value);
	boolean validateOutputPorts(EList<OutputPort> value);
	boolean validateStart(boolean value);
	boolean validateType(String value);
	boolean validateLabel(String value);
	boolean validateUrl(String value);
	boolean validateVersion(String value);
	boolean validateStatus(String value);
	boolean validatePublic(boolean value);
	boolean validateMulticore(boolean value);
	boolean validateConductors(EList<Conductor> value);
}
